#include <opencv2/calib3d.hpp>
#include <opencv2/core.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>

#include <algorithm>
#include <charconv>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

namespace {

struct Options {
    std::string source = "v4l2src device=/dev/video0 ! image/jpeg,width=1280,height=720,framerate=60/1 "
                         "! jpegdec ! videoconvert ! video/x-raw,format=BGR "
                         "! appsink drop=true max-buffers=1 sync=false";
    std::string output = "/tmp/camera_calibration.yaml";
    int cols = 9;
    int rows = 6;
    int samples = 25;
    float square_mm = 25.0F;
};

[[noreturn]] void usage(const char* program, int status) {
    std::fprintf(status == 0 ? stdout : stderr,
        "Usage: %s [--source <device|pipeline>] [--cols 9] [--rows 6]\n"
        "          [--square-mm 25] [--samples 25] [--output <yaml>]\n"
        "Controls: SPACE capture, ENTER calibrate, U toggle undistort, Q/ESC quit\n",
        program);
    std::exit(status);
}

Options parse_args(int argc, char** argv) {
    Options options;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        auto next = [&](const char* name) -> const char* {
            if (++i >= argc) {
                std::fprintf(stderr, "Missing value for %s\n", name);
                usage(argv[0], 2);
            }
            return argv[i];
        };
        if (arg == "--source") options.source = next("--source");
        else if (arg == "--output") options.output = next("--output");
        else if (arg == "--cols") options.cols = std::atoi(next("--cols"));
        else if (arg == "--rows") options.rows = std::atoi(next("--rows"));
        else if (arg == "--samples") options.samples = std::atoi(next("--samples"));
        else if (arg == "--square-mm") options.square_mm = std::strtof(next("--square-mm"), nullptr);
        else if (arg == "-h" || arg == "--help") usage(argv[0], 0);
        else {
            std::fprintf(stderr, "Unknown argument: %s\n", arg.c_str());
            usage(argv[0], 2);
        }
    }
    if (options.cols < 2 || options.rows < 2 || options.samples < 10 ||
        !std::isfinite(options.square_mm) || options.square_mm <= 0.0F) {
        std::fprintf(stderr, "cols/rows must be >= 2, samples >= 10, and square-mm > 0\n");
        usage(argv[0], 2);
    }
    return options;
}

bool parse_device(const std::string& source, int& index) {
    if (source.empty()) return false;
    const auto result = std::from_chars(source.data(), source.data() + source.size(), index);
    return result.ec == std::errc {} && result.ptr == source.data() + source.size();
}

std::vector<cv::Point3f> make_object_points(cv::Size board, float square_mm) {
    std::vector<cv::Point3f> points;
    points.reserve(static_cast<std::size_t>(board.area()));
    for (int row = 0; row < board.height; ++row)
        for (int col = 0; col < board.width; ++col)
            points.emplace_back(col * square_mm, row * square_mm, 0.0F);
    return points;
}

double view_error(const std::vector<cv::Point3f>& object_points,
                  const std::vector<cv::Point2f>& image_points,
                  const cv::Mat& rvec, const cv::Mat& tvec,
                  const cv::Mat& matrix, const cv::Mat& distortion) {
    std::vector<cv::Point2f> projected;
    cv::projectPoints(object_points, rvec, tvec, matrix, distortion, projected);
    return cv::norm(image_points, projected, cv::NORM_L2) /
           std::sqrt(static_cast<double>(image_points.size()));
}

bool write_yaml(const std::string& path, cv::Size image_size,
                const cv::Mat& matrix, const cv::Mat& distortion,
                double rms, double mean_error) {
    std::ofstream output(path);
    if (!output) return false;
    output << std::setprecision(12)
           << "# Generated by camera_calib\n"
           << "# OpenCV RMS: " << rms << " px; mean per-view error: " << mean_error << " px\n"
           << "camera:\n"
           << "  matrix: [" << matrix.at<double>(0, 0) << ", 0, " << matrix.at<double>(0, 2)
           << ", 0, " << matrix.at<double>(1, 1) << ", " << matrix.at<double>(1, 2)
           << ", 0, 0, 1]\n"
           << "  distortion: [" << distortion.at<double>(0) << ", " << distortion.at<double>(1)
           << ", " << distortion.at<double>(2) << ", " << distortion.at<double>(3)
           << ", " << distortion.at<double>(4) << "]\n"
           << "  image_width: " << image_size.width << "\n"
           << "  image_height: " << image_size.height << "\n";
    return output.good();
}

}  // namespace

int main(int argc, char** argv) {
    const auto options = parse_args(argc, argv);
    cv::VideoCapture capture;
    int device = 0;
    const bool opened = parse_device(options.source, device)
        ? capture.open(device)
        : capture.open(options.source, cv::CAP_GSTREAMER);
    if (!opened) {
        std::fprintf(stderr, "Failed to open camera source: %s\n", options.source.c_str());
        return 3;
    }

    const cv::Size board { options.cols, options.rows };
    const auto object_template = make_object_points(board, options.square_mm);
    std::vector<std::vector<cv::Point2f>> image_points;
    cv::Size image_size;
    cv::Mat matrix, distortion;
    bool calibrated = false;
    bool show_undistorted = false;
    double rms = 0.0;
    double mean_error = 0.0;
    const std::string window = "camera_calib";
    cv::namedWindow(window, cv::WINDOW_NORMAL);

    std::cout << "Board: " << options.cols << 'x' << options.rows << " inner corners, square "
              << options.square_mm << " mm\n"
              << "Move and tilt the board across the whole image. Press SPACE to capture.\n";

    for (;;) {
        cv::Mat frame;
        if (!capture.read(frame) || frame.empty()) {
            std::fprintf(stderr, "Camera read failed\n");
            return 4;
        }
        if (image_size.empty()) image_size = frame.size();
        if (frame.size() != image_size) {
            std::fprintf(stderr, "Camera resolution changed during calibration\n");
            return 5;
        }

        cv::Mat gray;
        cv::cvtColor(frame, gray, cv::COLOR_BGR2GRAY);
        std::vector<cv::Point2f> corners;
        // The sector-based detector is substantially more robust than the classic
        // detector under perspective, uneven illumination and large corner grids.
        // Its returned corners are already refined to sub-pixel accuracy.
        const bool found = cv::findChessboardCornersSB(
            gray, board, corners,
            cv::CALIB_CB_NORMALIZE_IMAGE | cv::CALIB_CB_EXHAUSTIVE | cv::CALIB_CB_ACCURACY);

        cv::Mat display;
        if (calibrated && show_undistorted)
            cv::undistort(frame, display, matrix, distortion);
        else
            display = frame.clone();
        if (!show_undistorted) cv::drawChessboardCorners(display, board, corners, found);
        const cv::Scalar status_color = found ? cv::Scalar(0, 220, 0) : cv::Scalar(0, 80, 255);
        cv::putText(display,
            cv::format("Samples: %zu/%d  Corners: %s", image_points.size(), options.samples,
                       found ? "FOUND" : "not found"),
            cv::Point(20, 35), cv::FONT_HERSHEY_SIMPLEX, 0.8, status_color, 2);
        if (calibrated) {
            cv::putText(display, cv::format("RMS %.3f px  mean %.3f px%s", rms, mean_error,
                        show_undistorted ? "  UNDISTORTED" : ""),
                cv::Point(20, 70), cv::FONT_HERSHEY_SIMPLEX, 0.7, cv::Scalar(255, 200, 0), 2);
        }
        cv::imshow(window, display);

        const int key = cv::waitKey(1) & 0xff;
        if (key == 'q' || key == 27) break;
        if (key == 'u' && calibrated) show_undistorted = !show_undistorted;
        if (key == ' ' && found && static_cast<int>(image_points.size()) < options.samples) {
            image_points.push_back(corners);
            std::cout << "Captured " << image_points.size() << '/' << options.samples << '\n';
        }
        const bool requested = key == 10 || key == 13 ||
                               (!calibrated &&
                                static_cast<int>(image_points.size()) >= options.samples);
        if (!requested) continue;
        if (image_points.size() < 10) {
            std::cout << "Need at least 10 samples; currently " << image_points.size() << '\n';
            continue;
        }

        std::vector<std::vector<cv::Point3f>> object_points(image_points.size(), object_template);
        std::vector<cv::Mat> rvecs, tvecs;
        matrix = cv::Mat::eye(3, 3, CV_64F);
        distortion = cv::Mat::zeros(5, 1, CV_64F);
        rms = cv::calibrateCamera(object_points, image_points, image_size, matrix, distortion,
                                  rvecs, tvecs);
        double error_sum = 0.0;
        double worst_error = 0.0;
        for (std::size_t i = 0; i < image_points.size(); ++i) {
            const double error = view_error(object_points[i], image_points[i], rvecs[i], tvecs[i],
                                            matrix, distortion);
            error_sum += error;
            worst_error = std::max(worst_error, error);
            std::cout << "view " << (i + 1) << ": " << std::fixed << std::setprecision(3)
                      << error << " px\n";
        }
        mean_error = error_sum / static_cast<double>(image_points.size());
        calibrated = cv::checkRange(matrix) && cv::checkRange(distortion);
        if (!calibrated) {
            std::fprintf(stderr, "Calibration produced invalid values\n");
            continue;
        }
        if (!write_yaml(options.output, image_size, matrix, distortion, rms, mean_error)) {
            std::fprintf(stderr, "Failed to write: %s\n", options.output.c_str());
            return 6;
        }
        std::cout << "RMS: " << rms << " px, mean: " << mean_error
                  << " px, worst: " << worst_error << " px\n"
                  << "Saved: " << options.output << "\n"
                  << "Press U to inspect undistortion, Q to quit.\n";
    }
    return calibrated ? 0 : 1;
}
