// gimbal_extrinsic_calib —— 陀螺仪-相机外参标定工具
// 使用方式：让云台在不同姿态下采集帧，工具自动积累 (camera→target_rotation, imu_rotation) 对
// 最后输出 camera→imu 的旋转矩阵，写入 camera.transform 的 orientation 字段

#include "core/config_loader.hpp"
#include "core/frame_source.hpp"
#include "core/gimbal_extrinsic.hpp"
#include "core/rune_pnp.hpp"
#include "core/conversion.hpp"

#include <eigen3/Eigen/Geometry>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numbers>
#include <random>
#include <vector>

namespace {

constexpr auto kRadToDeg = 180.0 / std::numbers::pi;

struct Options {
    std::string config = "config/camera_sentry.yaml";
    std::string source;
    std::string output = "/tmp/gimbal_extrinsic.yaml";
    bool self_test = false;
};

[[noreturn]] void usage(const char* program, int status) {
    std::fprintf(status == 0 ? stdout : stderr,
        "Usage: %s [-c config.yaml] [--source DEVICE|PIPELINE] [--output result.yaml] [--self-test]\n"
        "Controls: SPACE capture sample, Q quit\n"
        "  --self-test: Run synthetic test (no camera needed)\n",
        program);
    std::exit(status);
}

Options parse_args(int argc, char** argv) {
    Options options;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        auto next = [&](const char* name) -> const char* {
            if (++i >= argc) {
                std::fprintf(stderr, "Missing value for %s\n", name);
                usage(argv[0], 2);
            }
            return argv[i];
        };
        if (arg == "-c" || arg == "--config") options.config = next("--config");
        else if (arg == "--source") options.source = next("--source");
        else if (arg == "--output") options.output = next("--output");
        else if (arg == "--self-test") options.self_test = true;
        else if (arg == "-h" || arg == "--help") usage(argv[0], 0);
        else {
            std::fprintf(stderr, "Unknown argument: %s\n", arg.c_str());
            usage(argv[0], 2);
        }
    }
    return options;
}

// 生成合成测试数据：真实的 camera→imu 旋转，然后生成多组变换对
auto generate_synthetic_samples(int num_samples = 5) -> std::vector<rmcs::ExtrinsicSample> {
    std::mt19937 rng(42);
    std::uniform_real_distribution<double> angle_dist(-std::numbers::pi, std::numbers::pi);

    // 真实的 camera→imu 旋转（模拟装配时的偏置）
    Eigen::AngleAxisd true_rotation(angle_dist(rng), Eigen::Vector3d::Random().normalized());
    Eigen::Matrix3d R_cam_imu = true_rotation.toRotationMatrix();

    std::printf("Synthetic test: True camera→IMU rotation:\n");
    std::printf("  Angle: %.3f deg, Axis: (%.3f, %.3f, %.3f)\n",
        true_rotation.angle() * kRadToDeg,
        true_rotation.axis().x(), true_rotation.axis().y(), true_rotation.axis().z());

    std::vector<rmcs::ExtrinsicSample> samples;

    // 生成 N 组随机的相机观测和对应的 IMU 读数
    for (int i = 0; i < num_samples; ++i) {
        // 随机相机→目标旋转（模拟不同的符号姿态）
        Eigen::AngleAxisd cam_rot(angle_dist(rng), Eigen::Vector3d::Random().normalized());
        Eigen::Matrix3d A = cam_rot.toRotationMatrix();

        // 对应的 IMU→基座旋转（满足 A·X = X·B，即 B = X^{-1}·A·X）
        Eigen::Matrix3d B = R_cam_imu.inverse() * A * R_cam_imu;

        samples.push_back({A, B});
        std::printf("Sample %d: camera→target angle=%.1f°, imu→base angle=%.1f°\n",
            i + 1, cam_rot.angle() * kRadToDeg, Eigen::AngleAxisd(B).angle() * kRadToDeg);
    }

    return samples;
}

bool write_yaml(const std::string& path, const Eigen::Quaterniond& q_cam_imu) {
    std::ofstream yaml(path);
    if (!yaml) return false;
    yaml << std::setprecision(12)
         << "# Generated by gimbal_extrinsic_calib\n"
         << "camera:\n"
         << "  transform: [0, 0, 0, " << q_cam_imu.x() << ", " << q_cam_imu.y() << ", "
         << q_cam_imu.z() << ", " << q_cam_imu.w() << "]\n";
    return yaml.good();
}

}  // namespace

int main(int argc, char** argv) {
    auto options = parse_args(argc, argv);

    // Self-test mode: generate synthetic samples and solve without camera/IMU
    if (options.self_test) {
        std::printf("=== Self-Test Mode ===\n");
        auto samples = generate_synthetic_samples(5);

        auto rotation = rmcs::solve_gimbal_extrinsic(samples);
        if (!rotation) {
            std::fprintf(stderr, "Failed to solve extrinsic (SVD failure)\n");
            return 6;
        }

        Eigen::Quaterniond q_cam_imu(*rotation);
        q_cam_imu.normalize();

        std::printf("\nSolved camera→IMU rotation:\n");
        std::printf("  Quaternion: x=%f y=%f z=%f w=%f\n",
            q_cam_imu.x(), q_cam_imu.y(), q_cam_imu.z(), q_cam_imu.w());

        if (!write_yaml(options.output, q_cam_imu)) {
            std::fprintf(stderr, "Failed to write: %s\n", options.output.c_str());
            return 6;
        }
        std::printf("Saved to: %s\n", options.output.c_str());
        return 0;
    }

    // Normal mode: capture from camera (not yet implemented)
    std::printf("=== Normal Mode (Camera Capture) ===\n");
    std::printf("TODO: Implement camera + PnP integration\n");
    std::printf("For now, use --self-test to verify the solver algorithm.\n");
    return 0;
}
